parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: aronet_orlik
    database_user: aronet_orlik
    database_password: haslo123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: efef1e56d81ff0ca52b8f710f6f7bf921
    database_path: null
