<?php

namespace Cup\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cup_group_teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CupGroupTeamRepository extends EntityRepository
{
}
