<?php

namespace Cup\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cup_matchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CupMatchRepository extends EntityRepository
{
}
