<?php

namespace Cup\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CupTeamMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CupTeamMatchRepository extends EntityRepository
{
}
