<?php

namespace Cup\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Cup\HomeBundle\Entity\CupTeam;
/**
 * cup_teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CupTeamRepository extends EntityRepository
{
    public function getListForForm()
    {
        $em = $this->getEntityManager();
        $gb = $em->createQueryBuilder();
        $gb->select('t.id, t.name')
            ->from('CupHomeBundle:CupTeam', 't')
            ->orderBy('t.name', 'ASC');
        $query = $gb->getQuery();
        $teams = $query->getResult();
        $result = array();

        foreach ($teams as $t) {
            $result[$t['id']] = $t['name'];
        }

        return $result;
    }
}
