parameters:
    cup_match.data.provider.class: Cup\HomeBundle\DataProvider\CupMatchProvider
    cup_user_beat.data.provider.class: Cup\HomeBundle\DataProvider\MyBeatProvider
#    cup_home.example.class: Cup\HomeBundle\Example

services:
    cup_match.data.provider:
        class: %cup_match.data.provider.class%
        arguments:
            entityManager: "@doctrine.orm.default_entity_manager"
    user_beat.data.provider:
        class: %cup_user_beat.data.provider.class%
        arguments:
            entityManager: "@doctrine.orm.default_entity_manager"

#    cup_home.example:
#        class: %cup_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
