skoki_orlik_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SkokiOrlikBundle:Default:index }

orlik_homepage:
    pattern:  /
    defaults: { _controller: SkokiOrlikBundle:Default:homepage }

_show_table:
    pattern: /table
    defaults: { _controller: SkokiOrlikBundle:Table:showTable }

_orlik_show_team:
    path: /team/show/{id}
    defaults: { _controller: SkokiOrlikBundle:Team:show }
    methods: GET

_show_teams_list:
    path: /team/list
    defaults: { _controller: SkokiOrlikBundle:Team:list }
_orlik_timetable:
    pattern: /timetable
    defaults: { _controller: SkokiOrlikBundle:Timetable:index }

_orlik_show_timetable:
    pattern: /timetable/show
    defaults: { _controller: SkokiOrlikBundle:Timetable:showTimetable }

_orlik_show_match:
    pattern: /match/show/{id}
    defaults: { _controller: SkokiOrlikBundle:Match:show }

_match_update:
    pattern: /match/{id}/update
    defaults: { _controller: SkokiOrlikBundle:Match:update }
    methods: GET

_match_update_process:
    pattern: /match/{id}/update
    defaults: { _controller: SkokiOrlikBundle:Match:update }
    methods: POST