skoki_orlik_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SkokiOrlikBundle:Default:index }

orlik_homepage:
    pattern:  /
    defaults: { _controller: SkokiOrlikBundle:Default:homepage }
