parameters:
#    skoki_orlik.example.class: Skoki\OrlikBundle\Example

services:
#    skoki_orlik.example:
#        class: %skoki_orlik.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
