parameters:
    orlik_match.manager.class: Skoki\OrlikBundle\Model\MatchManager
#    skoki_orlik.example.class: Skoki\OrlikBundle\Example

services:
    match_manager:
        class: "%orlik_match.manager.class%"
        arguments: [@doctrine.orm.default_entity_manager]
#    skoki_orlik.example:
#        class: %skoki_orlik.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
