<?php

namespace Skoki\OrlikBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatTableRepository extends EntityRepository
{
}
