<?php

namespace Skoki\OrlikBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchesRepository extends EntityRepository
{
    public function getMatchList($teamId = null)
    {
        $em = $this->getEntityManager();
        $gb = $em->createQueryBuilder();
        $gb->select('m')
            ->from('SkokiOrlikBundle:Matches', 'm')
//            ->join('SkokiOrlikBundle:Teams', 't')
//            ->leftJoin('tc.user', 't')
//            ->where('m.id = tm.match_id')
//            ->andWhere('t.id = tm.home')
            ->orderBy('m.matchDate', 'DESC');

        if ($teamId !== null) {
            $gb->add('where',$gb->expr()->orX(
                $gb->expr()->eq('m.home', '?1'),
                $gb->expr()->eq('m.away', '?1')
            ));
            $gb->setParameters(array(1 => $teamId));
        }

        $query = $gb->getQuery();
        if ($teamId == null) {
            $teams = $query->getArrayResult();
        } else {
            $teams = $query->getResult();
        }

        return $teams;

    }

    public function getListWithTeams($teamId = null, $round = null)
    {
        $em = $this->getEntityManager();
        $gb = $em->createQueryBuilder();
        $gb->select('m.id, m.matchDate, m.home, m.away, t.name, t.id as team_id, m.result')
            ->from('SkokiOrlikBundle:Matches', 'm')
            ->join('SkokiOrlikBundle:Teams', 't')
//            ->leftJoin('tc.user', 't')
            ->where('m.home = t.id')
            ->orWhere('m.away = t.id')
            ->orderBy('m.matchDate', 'DESC');
        if ($teamId !== null) {
            $gb->add('where',$gb->expr()->orX(
                $gb->expr()->eq('m.home', '?1'),
                $gb->expr()->eq('m.away', '?1')
            ));
            $gb->setParameters(array(1 => $teamId));
        }
        if ($round !== null) {
//            $mm = '';
//            foreach ($machesList as $m) {
//                $mm .= '"' . $m . '",';
//            }
            $gb->add('where',$gb->expr()->eq('m.rounds', '?2'));
            $gb->setParameters(array(2 => $round));
        }

        $query = $gb->getQuery();

        $teams = $query->getArrayResult();
        $result = array();

        foreach ($teams as $t) {
            $result[$t['id']]['id'] = $t['id'];
            $result[$t['id']]['matchDate'] = $t['matchDate'];
            $result[$t['id']]['score'] = $t['result'];
            if ($t['home'] === $t['team_id']) {
                $result[$t['id']]['home'] = $t['name'];
                $result[$t['id']]['home_id'] = $t['team_id'];
            }
            if ($t['away'] === $t['team_id']) {
                $result[$t['id']]['away'] = $t['name'];
                $result[$t['id']]['away_id'] = $t['team_id'];
            }
        }

        return $result;

    }
}
